export const doctors_data = 
[{
  "id": 8072,
  "full_name": "Michael Johnson",
  "email": "tpowling0@biblegateway.com",
  "gender": "Nam",
  "birthdate": "8/12/1956",
  "hometown": "Phan Thiet",
  "faculty": "Khoa truyền nhiễm",
  "job": "Bác sĩ",
  "phone": "410-944-5272",
  "address": "15 Columbus Drive"
}, {
  "id": 3943,
  "full_name": "Kevin Lee",
  "email": "wbunny1@360.cn",
  "gender": "Nam",
  "birthdate": "12/17/1986",
  "hometown": "Hai Phong",
  "faculty": "Khoa sản",
  "job": "Bác sĩ",
  "phone": "184-702-4070",
  "address": "298 John Wall Pass"
}, {
  "id": 9303,
  "full_name": "Sarah Brown",
  "email": "wtredget2@europa.eu",
  "gender": "Nữ",
  "birthdate": "8/9/1960",
  "hometown": "Hai Phong",
  "faculty": "Khoa truyền nhiễm",
  "job": "Bác sĩ",
  "phone": "987-727-2393",
  "address": "6 Oak Valley Pass"
}, {
  "id": 4767,
  "full_name": "Jane Smith",
  "email": "fflorey3@behance.net",
  "gender": "Nữ",
  "birthdate": "10/25/1972",
  "hometown": "Da Nang",
  "faculty": "Khoa nhi",
  "job": "Bác sĩ",
  "phone": "681-757-6822",
  "address": "194 Pierstorff Court"
}, {
  "id": 2388,
  "full_name": "John Doe",
  "email": "bsymington4@ycombinator.com",
  "gender": "Nam",
  "birthdate": "6/20/1960",
  "hometown": "Phan Thiet",
  "faculty": "Khoa nội",
  "job": "Bác sĩ",
  "phone": "729-805-4314",
  "address": "8584 Mayfield Pass"
}, {
  "id": 6464,
  "full_name": "Sarah Brown",
  "email": "askuce5@squarespace.com",
  "gender": "Nữ",
  "birthdate": "12/21/1962",
  "hometown": "Da Nang",
  "faculty": "Khoa nhi",
  "job": "Bác sĩ",
  "phone": "922-497-9089",
  "address": "029 Pennsylvania Drive"
}, {
  "id": 2242,
  "full_name": "David Wilson",
  "email": "vfermer6@forbes.com",
  "gender": "Nam",
  "birthdate": "5/27/1967",
  "hometown": "Quy Nhon",
  "faculty": "Khoa sản",
  "job": "Bác sĩ",
  "phone": "330-105-2182",
  "address": "6776 Glacier Hill Place"
}, {
  "id": 7318,
  "full_name": "Brian Martinez",
  "email": "gdessent7@upenn.edu",
  "gender": "Nữ",
  "birthdate": "2/3/1982",
  "hometown": "Quy Nhon",
  "faculty": "Khoa ngoại",
  "job": "Bác sĩ",
  "phone": "461-361-9633",
  "address": "194 Lakeland Point"
}, {
  "id": 3474,
  "full_name": "Amanda Taylor",
  "email": "fcockland8@ehow.com",
  "gender": "Nam",
  "birthdate": "2/26/1956",
  "hometown": "Quy Nhon",
  "faculty": "Khoa sản",
  "job": "Bác sĩ",
  "phone": "499-983-7853",
  "address": "63 Utah Pass"
}, {
  "id": 6295,
  "full_name": "Brian Martinez",
  "email": "mantonsson9@163.com",
  "gender": "Nữ",
  "birthdate": "2/25/1973",
  "hometown": "Da Nang",
  "faculty": "Khoa truyền nhiễm",
  "job": "Bác sĩ",
  "phone": "259-438-8635",
  "address": "9 Superior Point"
}, {
  "id": 3365,
  "full_name": "John Doe",
  "email": "panderla@topsy.com",
  "gender": "Nam",
  "birthdate": "2/18/1972",
  "hometown": "Vung Tau",
  "faculty": "Khoa nội",
  "job": "Bác sĩ",
  "phone": "142-685-1411",
  "address": "229 Southridge Plaza"
}, {
  "id": 2805,
  "full_name": "Emily Davis",
  "email": "aburlesb@java.com",
  "gender": "Nữ",
  "birthdate": "8/23/1973",
  "hometown": "Nha Trang",
  "faculty": "Khoa sản",
  "job": "Bác sĩ",
  "phone": "614-220-7137",
  "address": "4968 Forest Dale Junction"
}, {
  "id": 8714,
  "full_name": "John Doe",
  "email": "cblaberc@loc.gov",
  "gender": "Nữ",
  "birthdate": "3/8/1968",
  "hometown": "Quy Nhon",
  "faculty": "Khoa truyền nhiễm",
  "job": "Bác sĩ",
  "phone": "603-747-7046",
  "address": "60340 Cody Trail"
}, {
  "id": 1455,
  "full_name": "Michael Johnson",
  "email": "mheapsd@google.it",
  "gender": "Nam",
  "birthdate": "12/1/1958",
  "hometown": "Quy Nhon",
  "faculty": "Khoa sản",
  "job": "Bác sĩ",
  "phone": "447-831-6617",
  "address": "4204 Gerald Hill"
}, {
  "id": 7009,
  "full_name": "Michael Johnson",
  "email": "alaxtonnee@squarespace.com",
  "gender": "Nam",
  "birthdate": "9/26/1973",
  "hometown": "Can Tho",
  "faculty": "Khoa sản",
  "job": "Bác sĩ",
  "phone": "763-229-0116",
  "address": "02706 Eggendart Lane"
}, {
  "id": 2444,
  "full_name": "John Doe",
  "email": "sscrinagef@tripod.com",
  "gender": "Nữ",
  "birthdate": "2/14/1978",
  "hometown": "Nha Trang",
  "faculty": "Khoa ngoại",
  "job": "Bác sĩ",
  "phone": "869-628-7255",
  "address": "5260 Oxford Lane"
}, {
  "id": 5354,
  "full_name": "Brian Martinez",
  "email": "mginng@ucla.edu",
  "gender": "Nam",
  "birthdate": "12/16/1969",
  "hometown": "Can Tho",
  "faculty": "Khoa nội",
  "job": "Bác sĩ",
  "phone": "868-976-7709",
  "address": "4119 Montana Point"
}, {
  "id": 5419,
  "full_name": "David Wilson",
  "email": "strowellh@netvibes.com",
  "gender": "Nữ",
  "birthdate": "4/16/1985",
  "hometown": "Hai Phong",
  "faculty": "Khoa nội",
  "job": "Bác sĩ",
  "phone": "126-284-8703",
  "address": "683 Harbort Terrace"
}, {
  "id": 7467,
  "full_name": "Laura Anderson",
  "email": "sstoneleyi@webeden.co.uk",
  "gender": "Nữ",
  "birthdate": "11/18/1994",
  "hometown": "Nha Trang",
  "faculty": "Khoa ngoại",
  "job": "Bác sĩ",
  "phone": "397-834-5958",
  "address": "0827 Hoepker Alley"
}, {
  "id": 2054,
  "full_name": "Amanda Taylor",
  "email": "jkyntonj@multiply.com",
  "gender": "Nam",
  "birthdate": "6/1/1993",
  "hometown": "Nha Trang",
  "faculty": "Khoa sản",
  "job": "Bác sĩ",
  "phone": "515-503-3414",
  "address": "10 Springview Terrace"
}]
