export const nurses_data =
[{
  "id": 2648,
  "full_name": "Kevin Lee",
  "email": "adear0@istockphoto.com",
  "gender": "Nữ",
  "birthdate": "6/7/1979",
  "hometown": "Nha Trang",
  "faculty": "Khoa sản",
  "job": "Y tá",
  "phone": "697-708-2081",
  "address": "26 Charing Cross Court"
}, {
  "id": 9628,
  "full_name": "Michael Johnson",
  "email": "sbiskupek1@eventbrite.com",
  "gender": "Nam",
  "birthdate": "7/8/1952",
  "hometown": "Hanoi",
  "faculty": "Khoa truyền nhiễm",
  "job": "Y tá",
  "phone": "202-830-6949",
  "address": "73 Spenser Avenue"
}, {
  "id": 7138,
  "full_name": "Brian Martinez",
  "email": "iletrange2@stumbleupon.com",
  "gender": "Nam",
  "birthdate": "8/8/1955",
  "hometown": "Hue",
  "faculty": "Khoa nhi",
  "job": "Y tá",
  "phone": "624-140-3247",
  "address": "5627 Stoughton Drive"
}, {
  "id": 3179,
  "full_name": "Amanda Taylor",
  "email": "paplin3@mtv.com",
  "gender": "Nữ",
  "birthdate": "8/22/1992",
  "hometown": "Hue",
  "faculty": "Khoa truyền nhiễm",
  "job": "Y tá",
  "phone": "363-257-4105",
  "address": "13 Paget Parkway"
}, {
  "id": 6103,
  "full_name": "Amanda Taylor",
  "email": "sfurness4@yahoo.com",
  "gender": "Nam",
  "birthdate": "3/2/1976",
  "hometown": "Hai Phong",
  "faculty": "Khoa nhi",
  "job": "Y tá",
  "phone": "102-699-4842",
  "address": "22 Parkside Place"
}, {
  "id": 8200,
  "full_name": "Kevin Lee",
  "email": "cghelardoni5@upenn.edu",
  "gender": "Nam",
  "birthdate": "4/30/1981",
  "hometown": "Vung Tau",
  "faculty": "Khoa ngoại",
  "job": "Y tá",
  "phone": "832-934-0306",
  "address": "22 Springview Circle"
}, {
  "id": 8768,
  "full_name": "Michael Johnson",
  "email": "ovolett6@newyorker.com",
  "gender": "Nam",
  "birthdate": "11/11/1980",
  "hometown": "Nha Trang",
  "faculty": "Khoa nội",
  "job": "Y tá",
  "phone": "497-850-8363",
  "address": "728 Debs Way"
}, {
  "id": 4831,
  "full_name": "Emily Davis",
  "email": "lhowles7@google.fr",
  "gender": "Nam",
  "birthdate": "7/8/1989",
  "hometown": "Hue",
  "faculty": "Khoa sản",
  "job": "Y tá",
  "phone": "397-674-4119",
  "address": "33592 Grim Terrace"
}, {
  "id": 4941,
  "full_name": "Jane Smith",
  "email": "kguidotti8@nature.com",
  "gender": "Nam",
  "birthdate": "1/25/1958",
  "hometown": "Vung Tau",
  "faculty": "Khoa truyền nhiễm",
  "job": "Y tá",
  "phone": "279-315-3677",
  "address": "3517 Pankratz Park"
}, {
  "id": 3096,
  "full_name": "Michael Johnson",
  "email": "kjostan9@fotki.com",
  "gender": "Nữ",
  "birthdate": "5/10/1965",
  "hometown": "Da Nang",
  "faculty": "Khoa nhi",
  "job": "Y tá",
  "phone": "986-307-0762",
  "address": "31 Nobel Lane"
}, {
  "id": 5841,
  "full_name": "John Doe",
  "email": "bpierrepointa@upenn.edu",
  "gender": "Nam",
  "birthdate": "3/11/1971",
  "hometown": "Hai Phong",
  "faculty": "Khoa truyền nhiễm",
  "job": "Y tá",
  "phone": "400-624-0083",
  "address": "76724 Packers Way"
}, {
  "id": 9797,
  "full_name": "John Doe",
  "email": "bamberb@usgs.gov",
  "gender": "Nữ",
  "birthdate": "9/25/1965",
  "hometown": "Hanoi",
  "faculty": "Khoa nhi",
  "job": "Y tá",
  "phone": "856-694-4906",
  "address": "9 Anzinger Alley"
}, {
  "id": 9343,
  "full_name": "John Doe",
  "email": "gzanicchic@berkeley.edu",
  "gender": "Nữ",
  "birthdate": "12/12/1961",
  "hometown": "Phan Thiet",
  "faculty": "Khoa truyền nhiễm",
  "job": "Y tá",
  "phone": "505-449-4590",
  "address": "2 Springs Junction"
}, {
  "id": 5592,
  "full_name": "Kevin Lee",
  "email": "cmclised@bloomberg.com",
  "gender": "Nam",
  "birthdate": "10/11/1989",
  "hometown": "Ho Chi Minh City",
  "faculty": "Khoa sản",
  "job": "Y tá",
  "phone": "913-993-6235",
  "address": "3 Mcguire Center"
}, {
  "id": 3588,
  "full_name": "David Wilson",
  "email": "aocrevye@unicef.org",
  "gender": "Nam",
  "birthdate": "2/13/1987",
  "hometown": "Hanoi",
  "faculty": "Khoa sản",
  "job": "Y tá",
  "phone": "404-478-6832",
  "address": "4 Hanover Circle"
}, {
  "id": 3298,
  "full_name": "Jane Smith",
  "email": "rvallancef@desdev.cn",
  "gender": "Nữ",
  "birthdate": "12/18/1957",
  "hometown": "Hue",
  "faculty": "Khoa truyền nhiễm",
  "job": "Y tá",
  "phone": "577-312-2104",
  "address": "4 Roth Junction"
}, {
  "id": 7440,
  "full_name": "Kevin Lee",
  "email": "eickovicg@bravesites.com",
  "gender": "Nam",
  "birthdate": "8/9/1988",
  "hometown": "Da Nang",
  "faculty": "Khoa nội",
  "job": "Y tá",
  "phone": "108-164-5918",
  "address": "7 Acker Parkway"
}, {
  "id": 9707,
  "full_name": "Michael Johnson",
  "email": "pmilesh@aboutads.info",
  "gender": "Nữ",
  "birthdate": "12/15/1994",
  "hometown": "Hue",
  "faculty": "Khoa nhi",
  "job": "Y tá",
  "phone": "529-270-6016",
  "address": "71 Bunting Trail"
}, {
  "id": 5069,
  "full_name": "Laura Anderson",
  "email": "dsaywardi@dion.ne.jp",
  "gender": "Nữ",
  "birthdate": "2/5/1966",
  "hometown": "Can Tho",
  "faculty": "Khoa truyền nhiễm",
  "job": "Y tá",
  "phone": "671-923-6088",
  "address": "8399 Caliangt Road"
}, {
  "id": 2009,
  "full_name": "Michael Johnson",
  "email": "crosonij@miitbeian.gov.cn",
  "gender": "Nam",
  "birthdate": "6/30/1987",
  "hometown": "Quy Nhon",
  "faculty": "Khoa nhi",
  "job": "Y tá",
  "phone": "406-647-4517",
  "address": "472 Laurel Place"
}, {
  "id": 1400,
  "full_name": "David Wilson",
  "email": "rgrisbrookk@unblog.fr",
  "gender": "Nam",
  "birthdate": "8/8/1960",
  "hometown": "Can Tho",
  "faculty": "Khoa nội",
  "job": "Y tá",
  "phone": "161-909-0801",
  "address": "64417 Forest Hill"
}, {
  "id": 3287,
  "full_name": "Jane Smith",
  "email": "ngristl@eventbrite.com",
  "gender": "Nữ",
  "birthdate": "3/21/1963",
  "hometown": "Vung Tau",
  "faculty": "Khoa ngoại",
  "job": "Y tá",
  "phone": "857-430-2287",
  "address": "41 Westend Hill"
}, {
  "id": 3952,
  "full_name": "Kevin Lee",
  "email": "srosseym@networkadvertising.org",
  "gender": "Nữ",
  "birthdate": "5/26/1975",
  "hometown": "Nha Trang",
  "faculty": "Khoa nhi",
  "job": "Y tá",
  "phone": "854-581-5909",
  "address": "7 Red Cloud Place"
}, {
  "id": 3373,
  "full_name": "Laura Anderson",
  "email": "sfilippozzin@stumbleupon.com",
  "gender": "Nữ",
  "birthdate": "1/20/1963",
  "hometown": "Hanoi",
  "faculty": "Khoa nội",
  "job": "Y tá",
  "phone": "698-724-8481",
  "address": "6605 Prairie Rose Plaza"
}, {
  "id": 8025,
  "full_name": "Kevin Lee",
  "email": "ewetherillo@about.me",
  "gender": "Nam",
  "birthdate": "7/15/1988",
  "hometown": "Phan Thiet",
  "faculty": "Khoa nhi",
  "job": "Y tá",
  "phone": "960-763-8557",
  "address": "36201 Esch Avenue"
}, {
  "id": 7114,
  "full_name": "Jane Smith",
  "email": "bsoaresp@oaic.gov.au",
  "gender": "Nữ",
  "birthdate": "4/24/1979",
  "hometown": "Quy Nhon",
  "faculty": "Khoa nhi",
  "job": "Y tá",
  "phone": "272-943-2140",
  "address": "3488 Lyons Terrace"
}, {
  "id": 3833,
  "full_name": "Michael Johnson",
  "email": "gmilesopq@marketwatch.com",
  "gender": "Nam",
  "birthdate": "11/24/1981",
  "hometown": "Can Tho",
  "faculty": "Khoa truyền nhiễm",
  "job": "Y tá",
  "phone": "780-369-2056",
  "address": "58 Center Avenue"
}, {
  "id": 6090,
  "full_name": "Laura Anderson",
  "email": "lrumpr@imageshack.us",
  "gender": "Nam",
  "birthdate": "10/29/1969",
  "hometown": "Hue",
  "faculty": "Khoa nội",
  "job": "Y tá",
  "phone": "558-134-5535",
  "address": "9 Northwestern Pass"
}, {
  "id": 5712,
  "full_name": "Emily Davis",
  "email": "mbeagleholes@webs.com",
  "gender": "Nữ",
  "birthdate": "8/2/1991",
  "hometown": "Da Nang",
  "faculty": "Khoa truyền nhiễm",
  "job": "Y tá",
  "phone": "237-115-0867",
  "address": "94 Meadow Ridge Street"
}, {
  "id": 2324,
  "full_name": "Kevin Lee",
  "email": "lelsburyt@ebay.com",
  "gender": "Nữ",
  "birthdate": "5/10/1962",
  "hometown": "Vung Tau",
  "faculty": "Khoa truyền nhiễm",
  "job": "Y tá",
  "phone": "647-226-8965",
  "address": "4116 Coleman Trail"
}]
